### PR TITLE
Update action internals and bump major

### PR DESCRIPTION
**Pull request by rathpc**
This includes:
- Updating dependencies to latest
- Update package-lock.json to latest version
- Resolve lint issues as a result of updating deps
- Update action to run using node16
- Bump version to 2.0.0

### CODE REVIEW

**Comment by rathpc** [comment]
@dcoraboeuf when you have a chance this updates the action to use newer deps etc.

**Comment by dcoraboeuf** [comment]
Actually, checked and merged now. Thanks for your contribution!

**Comment by rathpc** [comment]
> Actually, checked and merged now. Thanks for your contribution!

Thank you, would you mind running your tag script tomorrow so this new version is available for use as well?

**Comment by dcoraboeuf** [comment]
> > Actually, checked and merged now. Thanks for your contribution!
> 
> Thank you, would you mind running your tag script tomorrow so this new version is available for use as well?

Done ! Versions 2 are available. Thanks again.

**Comment by rathpc** [comment]
@dcoraboeuf 👆 fyi

**Comment by dcoraboeuf** [comment]
Hi @rathpc ,

Sorry for the delays, but I was pretty busy elsewhere.

That's strange indeed. It's fixed now.

```
* f1202f9 - (HEAD -> main, tag: v2.0.1, tag: v2.0, tag: v2, origin/main, origin/HEAD) ci: setting up PRs (7 days ago) <Damien Coraboeuf>
* d6b76fd - ci: setting up PRs (7 days ago) <Damien Coraboeuf>
*   c041013 - (tag: v2.0.0) Merge pull request #4 from rathpc/rathpc/update-deps (7 days ago) <Damien Coraboeuf>
|\  
| * 3b4156c - Update action internals and bump major (8 days ago) <Steven Rathbauer>
|/  
*   3cd1e1f - Merge pull request #3 from nemerosa/dcoraboeuf-patch-1 (1 year, 9 months ago) <Damien Coraboeuf>
```

**Pull request merged**
